#+TITLE: UofT Undergraduate Winter Math Reading Group
#+DESCRIPTION: The website for a University of Toronto undergraduate reading group
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+HTML_HEAD: <style> body {font-size:15px;} </style>

* Information

Welcome to the website for the University of Toronto Undegraduate Winter Math Reading Group!

Over the 2020/2021 Christmas break, we will be reading the first few chapters of 
Michael Artin's /Algebra/. This book is supposed to provide a rigorous and engaging introduction to elementary abstract algebra (group theory, ring theory, etc.)

** Goals

The goals of this reading group are as follows:

- To read and gain an understanding for the first few chapters of Artin's textbook.
- To have weekly discussions about the previous week's readings and problems.
- To collaborate to create a communal set of solutions/lecture notes/cool diagrams/other resources which can be shared with others at the end of the break.

** Details

In this reading group, we respect copyright laws, so if you don't have a copy of Artin's book, you definitely *should not* Google "Artin Algebra PDF" and download the first link.

To communicate/ask questions during the week, we have a Discord server to which each member of the group will be invited.

Any inquiries about joining the reading group, or any other questions should be directed to: [[mailto:jack.ceroni@mail.utoronto.ca][jack.ceroni@mail.utoronto.ca]]

** Logistics

Please see [[https://lucaman99.github.io/math/artin/logistics.html][this]] page for more information about the logistics of the group.

* Schedule

Below is the tentative reading schedule. Note that we will be scheduling a meeting sometime during the week the December 7th to discuss the reading/meeting schedule, 
and other details. 

\\


| Week | Date                          | Details                                       |
|    0 | Friday December 11th, 2020    | Discussing the logistics of the reading group |
|    1 | Friday December 18th, 2020    | Discussing Week 1 readings and solutions      |
|    2 | Wednesday December 23rd, 2020 | Discussing Week 2 readings and solutions      |
|    3 | Wednesday December 30th, 2020 | Discussing Week 3 readings and solutions      |
|    4 | Wednesday January 6th, 2020   | Discussing Week 4 readings and solutions      |
|    5 | Saturday January 9th, 2020    | Final session and discussion, takeaways       |

\\

The weekly meeting room can be joined [[https://utoronto.zoom.us/j/89168691329][here]]. The passcode will be shared in the Discord server.

* Solutions and Notes

The notes and solutions created by the members of the group will be posted here each week.

* Further Resources

Under Construction

* People

Below is a list of members of the group:

- [[https://lucaman99.github.io][Jack Ceroni]] (Organizer)
- Maya Rehem
- Peter Ma
- Freeman Cheng
- Diba Heydary
- Daniel Mishan
