#+TITLE:My preferred method for proving Killing-Hopf
#+DESCRIPTION:Let's go
#+HTML_HEAD: <style>body { line-height:22px; font-size:15px; padding-top:20px;} #postamble {padding-top:10px;margin:auto;max-width:60em;} .author {text-align:left;}</style>

/Originally posted:/ April 23rd, 2026

----------------------

* Introduction

The goal of this short blog post will be to outline my preferred method for the proving the theorem of Killing and Hopf which classifies the
universal covers of complete, connected Riemannian manifolds of constant curvature. Lee's book does this through taking an unnecessary detour through
monodromy, and Do Carmo probably omits a lot of details. So we'll do it ourselves!

* Some preliminary results and local classification of constant curvature spaces

We first require a few preliminary results about when we can guarantee that a local isometry is a covering map (and object of great desire to topologists and geometers).
First, let us recall a basic result (that we will not prove here):

*Lemma 1.* If $f : M \to N$ with both $M$ and $N$ connected is a local isometry and $M$ is complete then $N$ is also complete and $f$ is a covering map.

Let us now briefly recall some facts about Jacobi fields, which are variation fields $J$ associated with variations through geodesics. Equivalently, they satisfy the Jacobi equation, $D_t^2 J + R(J, \dot{\gamma}) \dot{\gamma} = 0$
for $\gamma$ a geodesic.
It is easy to see that given a geodesic, a Jacobi field $J$ along $\gamma$ with $J(0)$ and $J'(0)$ prescribed exists and is unique. In the constant curvature case, it is pretty easy to see exactly
what the Jacobi fields must be. Indeed, suppose $M$ has constant sectional curvature $k$: know that in the constant-curvature setting

$$R(X, Y) Z = - k (\langle X, Z \rangle Y - \langle Y, Z \rangle X)$$

so that

$$R(J, \dot{\gamma}) \dot{\gamma} = k \langle \dot{\gamma}, \dot{\gamma} \rangle J - \langle J, \dot{\gamma} \rangle \dot{\gamma}$$

If we are interested in solving the Jacobi equation for the case of $J(0) = 0$ and $D_t J(0) = W \perp \dot{\gamma}(0)$, note that

$$\frac{d}{dt} \langle D_t J, \dot{\gamma} \rangle = \langle D_t^2 J, \dot{\gamma} \rangle = -R(J, \dot{\gamma}, \dot{\gamma}, \dot{\gamma}) = 0$$

which means that $\frac{d}{dt} \langle J, \dot{\gamma} \rangle = \langle D_t J, \dot{\gamma} \rangle = 0$ for all $t$ so $\langle J, \dot{\gamma} \rangle = 0$ as
well. From here, let $W(t)$ denote the parallel transport of $W$ along $\gamma$. Our desired Jacobi field will satisfy the equation $D_t^2 J + k \langle \dot{\gamma}, \dot{\gamma} \rangle J = 0$.
Note that $\langle \dot{\gamma}, \dot{\gamma} \rangle$ is constant. If we let $J(t) = f_{k, \gamma}(t) W(t)$ with

\begin{equation}
f_{k, \gamma}(t) = \begin{cases}
\frac{\sin(\sqrt{k} |\dot{\gamma}(0)| t)}{\sqrt{k} |\dot{\gamma}(0)|} & \text{if} \ k > 0 \\
t & \text{if} \ k = 0 \\
\frac{\sinh(\sqrt{-k} |\dot{\gamma}(0)| t)}{\sqrt{-k} |\dot{\gamma}(0)| } & \text{if} \ k < 0
\end{cases}
\end{equation}

then clearly, we will have produced the desired vector field. If we combine this result with the Gauss lemma, then we can immediately give a local classification result
for manifolds of constant curvature.

*Remark 2.* Before proceeding, let us briefly recall that if $V$ is an $n$ -dimensional real vector space, once we choose a basis $v_1, \dots, v_n$, we can write down global coordinates $x = (x^1, \dots, x^n)$
where $x^i : V \to \mathbb{R}$ is given by $x^i(c^j v_j) = c^i$. This immediately gives us a global frame $\frac{d}{dx^1}, \dots, \frac{d}{dx^n}$ for $TV$. This fact allows us to identify
$T_p V$ and $V$ via the isomorphism of vector spaces $\frac{d}{dx^i}\rvert_p \mapsto v_i$. The main thing worth noting is that this identification is actually canonical. If $w_1, \dots, w_n$ were a different basis and $y = (y^1, \dots, y^n)$
were the corresponding coordinate functions, then if we define $T : V \to V$ as $T v_j = w_j = T^{jk} v_k$, then $x^i(w_j) = T^{ji}$ so $x^i = \sum_j T^{ji} y^j$ and
$\frac{d}{dy^j} = \frac{d x^i}{d y^j} \frac{d}{dx^i} = T^{ji} \frac{d}{dx^i}$
Thus, sending $\frac{d}{dx^i}\rvert_p \mapsto v_i$ is equivalent to sending $\frac{d}{dy^j} \mapsto T^{ji} v_i = w^j$. Recall that the derivative of functions between any two finite-dimensional vector spaces is
well-defined, as these vector spaces may always be endowed with norms, and all such norms are equivalent. Thus, it is easy to see that given $v \in V$, we have derivation in $T_p V$ given by
$f \mapsto \frac{d}{dt}\rvert_{t = 0} f(p + tv) = v^j \frac{d f}{dx^j}\rvert_p$, hence the canonical identification of $V$ and $T_p V$ takes a vector to its associated directional derivative at $p$.
We will mostly be interested in using this identification in the case that $V = T_p M$ for some manifold $M$. In particular, we have a canonical identification $T_v T_p M \simeq T_p M$ for any $v \in T_p M$.
In the next section, I will denote elements of $T_p M$ with lowercase letters and their canonical counterpart in $T_v T_p M$ by an uppercase letter. For example, $w \in T_p M$ and $W \in T_v T_p M$.

To do the local classification, the idea is to write down an explicit form for the constant-curvature metric in Riemannian normal coordinates. Thus, we need to understand the pullback metric $\exp_p^{*} g$,
which means that we need to be able to compute $\langle (\exp_p)_{*}(U), (\exp_p)_{*}(W) \rangle$ for pairs of $U, W \in T_v B_{\varepsilon}(0)$ with $v \in B_{\varepsilon}(0) \subset T_p M$. The Gauss lemma
lets us do this in general for the case that $U = V$ (i.e. $U$ is the counterpart of $v$). In other words, when one of the tangent vectors in question is pointing in the radial direction:

*Lemma 3* (Gauss). $\langle (\exp_p)_{*, v}(V), (\exp_p)_{*, v}(W) \rangle = \langle v, w \rangle$ for $V, W \in T_v B_{\varepsilon}(0)$.

This is a basic result, so we'll skip its proof. So, all that remains is to calculate $\langle (\exp_p)_{*}(U), (\exp_p)_{*}(W) \rangle$ for pairs of
$U, W \in T_v B_{\varepsilon}(0)$ with $u$ and $w$ both orthogonal to $v$. Doing this without any extra assumptions is impossible,
but in the constant curvature setting, we can use our previous work with Jacobi fields. In particular, let $J_U$ be the Jacobi field along the geodesic $\gamma(t) = \exp_p(tv)$ with $J_U(0) = 0$
and $D_t J_U(0) = u \perp v = \dot{\gamma}(0)$. Define $J_W$ similarly. We know that in general these Jacobi fields will be given by $J_U(t) = (\exp_p)_{*, tv}(tU)$ where $U \in T_{tv} T_p M$ is the counterpart of $u$. $J_W$
is defined similarly. Thus, in particular, $J_U(1) = (\exp_p)_{*, v}(U)$ and $J_W(1) = (\exp_p)_{*, v}(W)$. We also know from our work above that
\begin{equation}
\langle J_U(t), J_W(t) \rangle = f_{k, \gamma}(t)^2 \langle u(t), w(t) \rangle
\end{equation}
where $u(t)$ and $w(t)$ are the parallel transports of $u$ and $w$ along $\gamma$. In particular, $\langle u(t), w(t) \rangle$ is constant, so
\begin{equation}
\langle (\exp_p)_{*, v}(U), (\exp_p)_{*, v}(W) \rangle = \langle J_U(1), J_W(1) \rangle = f_{k, \gamma}(1)^2 \langle u(1), w(1) \rangle = f_{k, \gamma}(1)^2 \langle u, w \rangle
\end{equation}

and we're done. From here, everything becomes easy. Suppose $(M, g)$ has constant curvature $k$. Pick $p \in M$, let $B = \exp_p(B_{\varepsilon}(0))$ be such that $\exp_p : B_{\varepsilon}(0) \to B$ is a local diffeomorphism.
In other words, $(\exp_p)_{*}$ doesn't drop rank on $B_{\varepsilon}(0)$. It could, however, be the case that $B$ is not a normal neighbourhood!

Let $e_1, \dots, e_n$ be an orthonormal basis for $T_p M$ (relative to $g_p$), let $\Phi : \mathbb{R}^n \to T_p M$ be the corresponding linear isomorphism with the standard Euclidean basis and let $\varphi = \Phi \circ \exp_p$.
Note that if $w^j \frac{d}{ds^j}$ is some Euclidean tangent vector at point $(v^1, \dots, v^n)$, then we obtain a corresponding tangent vector $w^j \Phi_{*}\left( \frac{d}{ds^j} \right) = w^j E_j$
in $T_v T_p M$ where $v = v^j e_j$. Pick some $v = (v^1, \dots, v^n)$ away from the origin in Euclidean space, note that the radial
vector $v^j \frac{d}{ds^j}$ at this point will be orthogonal to some $w^j \frac{d}{ds^j}$ if and only if $v^j e_j$ is orthogonal to $w^j e_j$ relative to $g_p$. Therefore, using the above results,

\begin{equation}
(\varphi^{*} g)_v\left( v^j \frac{d}{ds^j}, w^j \frac{d}{ds^j} \right) = \langle (\exp_p)_{*}(V), (\exp_p)_{*}(W) \rangle = \langle v^j e_j, w^j e_j \rangle = v^1 w^1 + \cdots + v^n w^n
\end{equation}
and for $w^j \frac{d}{ds^j}$ and $u^j \frac{d}{ds^j}$ both orthogonal to $v^j \frac{d}{ds^j}$,
\begin{equation}
(\varphi^{*} g)_v\left( w^j \frac{d}{ds^j}, u^j \frac{d}{ds^j} \right) = \langle (\exp_p)_{*}(W), (\exp_p)_{*}(U) \rangle = f_{k, \gamma}(1)^2 (u^1 w^1 + \cdots + u^n w^n)
\end{equation}
where
\begin{equation}
f_{k, \gamma}(1)^2 = \begin{cases}
\frac{\sin^2(\sqrt{k} r(v))}{k r(v)^2} & \text{if} \ k > 0 \\
1 & \text{if} \ k = 0 \\
-\frac{\sinh^2(\sqrt{-k} r(v))}{k r(v)^2 } & \text{if} \ k < 0
\end{cases}
\end{equation}
where $r(v) = \sqrt{(v^1)^2 + \cdots + (v^n)^2}$. Let $j : B_{\varepsilon}(0) - \{0\} \to \mathbb{R}^n - \{0\}$ be inclusion and define $\pi : \mathbb{R}^{n} - \{0\} \to S^{n - 1}$ as $\pi(v) = \frac{v}{r(v)}$.
Also let $\iota : S^{n - 1} \to \mathbb{R}^n$ be inclusion. Our goal is to now say what the metric on $B_{\varepsilon}(0) - \{0\}$ is, given the above formulas. It is easy to check that
$dr^2 + r^2 (j \circ \pi)^{*} g_{S^{n - 1}}$ gives the Euclidean metric on $B_{\varepsilon}(0) - \{0\}$, hence for vectors orthogonal to the radial vector, $r^2 (j \circ \pi)^{*} g_{S^{n - 1}}$ returns their Euclidean
inner product and kills the radial vector. It follows that $dr^2$ must return the Euclidean inner product of radial-pointing vectors and kill all vectors orthogonal to the radial direction. Thus,
on the punctured Euclidean disk $B_{\varepsilon}(0) - \{0\}$, we have
\begin{equation}
\varphi^{*} g = dr^2 + r^2 f_{k, \gamma}(1)^2 (j \circ \pi)^{*} g_{S^{n - 1}} = dr^2 + \rho_k(r) (j \circ \pi)^{*} g_{S^{n - 1}}
\end{equation}
where
\begin{equation}
\rho_k(r) = \begin{cases}
\frac{\sin^2(\sqrt{k} r)}{k} & \text{if} \ k > 0 \\
r^2 & \text{if} \ k = 0 \\
-\frac{\sinh^2(\sqrt{-k} r)}{k } & \text{if} \ k < 0
\end{cases}
\end{equation}

*Corollary 4.* Given two manifolds $(M, g)$ and $(N, h)$ of the same constant curvature, $p \in M$, $q \in N$, then any two normal neighbourhoods $\exp_p(B_{\varepsilon}(0))$ and $\exp_q(B_{\varepsilon}(0))$
of the same radius are isometric (where we allow $\varepsilon = \infty$).

/Proof./ Let $\varphi$ be the normal coordinates on $M$, $\psi$ the normal coordinates on $N$. In the Euclidean ball $B_{\varepsilon}(0)$, both
$\varphi^{*} g$ and $\psi^{*} h$ have the same form away from the origin, via the above discussion. By continuity, they must also agree at the origin, hence we immediately get an isometry.

* Hadamard's theorem

To prove Hadamard's theorem, we first need to use Jacobi fields as they were meant to be used: to understand how geodesics spread out when shot out from a given point.
Recall that if we take some $p \in M$, then another point $q$ is said to be /conjugate/ to $p$ if there exists a (non-zero) Jacobi field $J$ along a geodesic $\gamma$ between $p$ and $q$ which
vanishes at both $p$ and $q$. Thus, given $p$, a point $q$ is conjugate to $p$ if and only if there exist $v, w \in T_p M$ such that $\exp_p(v) = q$ and $(\exp_p)_{*, v}(W) = 0$. In
other words, $q$ is conjugate to $p$ if and only if it is a critical value of $\exp_p$. It follows that whenever we can lower-bound the norm of Jacobi fields in a given time interval,
we can guarantee that there are no conjugate points to $p$ in a region around it, and therefore that $\exp_p$ is a local diffeomorphism onto this region.

*Lemma 5.* If $M$ has non-positive (not necessarily constant) sectional curvature, then there are never conjugate points. Thus, $\exp_p$ is a local diffeomorphism
on its maximal domain of definition for any $p \in M$. In particular, if $M$ is complete, then $\exp_p : T_p M \to M$ is a local diffeomorphism for any $p \in M$.

/Proof./ Note that if $J$ is a Jacobi field along $\gamma$ starting at $p$ with $J(0) = 0$, then

\begin{equation}
\frac{d^2}{dt^2} \langle J, J \rangle = 2 \langle D_t J, D_t J \rangle - 2 \text{sec}(J, \dot{\gamma}) |J \wedge \dot{\gamma}|^2 \geq 0
\end{equation}
for all times $t$, so the function $t \mapsto \langle J(t), J(t) \rangle$ is convex. Clearly, it is $0$ at $t = 0$. Thus if it were true that $\langle J(s), J(s) \rangle = 0$
for some $s \neq 0$, then $J$ would necessarily have to vanish on the entire interval $[0, s]$ (or $[s, 0]$ is $s < 0$). But then the second derivative would have to vanish
on this whole interval. In particular, $\langle D_t J, D_t J \rangle$ would have to vanish at $0$, so by uniqueness of Jacobi fields, we would have $J = 0$.

*Lemma 6.* If $M$ has positive constant curvature $k > 0$, then given $p \in M$, there are no points conjugate to $p$ which lie a distance less than $\frac{\pi}{\sqrt{k}}$ away from $p$.
Thus, if $M$ is complete, then for any $p \in M$, $\exp_p : B_{\pi/\sqrt{k}}(0) \to M$ will be a local diffeomorphism.

/Proof./ Recall that in the constant curvature case, we have an explicit
form for Jacobi fields. We can always assume WLOG that $D_t J(0) \perp \dot{\gamma}(0)$ and $|\dot{\gamma}(0)| = 1$, and therefore that for some Jacobi field starting at $p$ with $J(0) = 0$,
\begin{equation}
\langle J(t), J(t) \rangle = \frac{\sin^2(\sqrt{k} t)}{k} \langle w(t), w(t) \rangle
\end{equation}
which is non-vanishing for $0 < t < \frac{\pi}{\sqrt{k}}$, as desired.

We've done most of the difficult work in proving Hadamard's theorem already. We just need to put it all together:

*Theorem 7* (Hadamard). If $(M, g)$ is a connected, complete Riemannian manifold of non-positive sectional curvature (not necessarily constant), then $\exp_p : T_p M \to M$ is a smooth covering map
for any $p \in M$. In the case that $M$ is simply-connected, it follows that this map is a diffeomorphism.

/Proof./ From Lemma 5, $\exp_p$ is a local diffeomorphism. If we endow $T_p M$ with the pullback metric $\exp_p^{*} g$, it becomes a local isometry. In $T_p M$, the straight line $t \mapsto tv$ defined
for all $t$ is sent by $\exp_p$ to the geodesic $\exp_p(tv)$. If we choose some $U$ around point $t_0 v$ where $\exp_p|_U : U \to \exp_p(U)$ is an isometry, it follows that the segment of $t \mapsto tv$
around $t_0 v$ contained in $U$ must be a geodesic. This holds around all points in this curve, thus the whole curve is a geodesic in $T_p M$ relative to the pullback metric. Since $T_p M$ has a single
point at which geodesics are defined for all time, it follows that the whole manifold $T_p M$ is complete (this is a consequence of the proof of Hopf-Rinow theorem). Therefore, it follows from
Lemma 1 that $\exp_p$ is a covering map.

This result is quite astounding. Some immediate corollaries can be stated:

*Corollary 8.* No manifold of the form $S^n \times M$ for $n \geq 2$ and $M^m$ complete/connected admits a metric of non-positive scalar curvature. If it did, then the universal covering manifold
$S^n \times \widetilde{M}$ would necessarily by diffeomorphic to $\mathbb{R}^{n + m}$, but $S^n \times \widetilde{M}$ has non-vanishing cohomology in the $n$ -th degree while $\mathbb{R}^{n + m}$ is
contractible so this cannot be.

*Corollary 9.* Any (complete/connected) $M$ admiting a metric of non-positive scalar curvature is aspherical: its only non-trivial, positive-degree homotopy group may be the fundamental group. This is because covering maps
induce isomorphisms of $\pi_k$ for $k \geq 2$, and $M$ has contractible universal cover.

* Killing-Hopf theorem

We have now come to the ultimate purpose of this post: proving Killing-Hopf.

*Theorem 10* (Killing-Hopf). If $(M, g)$ is complete and simply connected and constant sectional curvature $k \in \{-1, 0, 1\}$, it is isometric to $\{\mathbb{H}^n, \mathbb{R}^n, S^n\}$, which
we know have constant sectional curvature $\{-1, 0, 1\}$ respectively.

/Proof./ We already proved that $M$ will be /locally/ isometric to one of the given model spaces: the remaining question is whether this local isometry is in fact global.
For the case of $k = -1$, we know that $\exp_p : T_p M \to M$ and $\exp_q : T_q \mathbb{H}^n \to \mathbb{H}^n$ are diffeomorphisms, so from Corollary 4, $M = \exp_p(T_p M)$
and $\mathbb{H}^n = \exp_q(T_q \mathbb{H}^n)$ are isometric as normal neighbourhoods. The case of $k = 0$ is proved in the same way.

In the case of $k = 1$, we /cannot/ use Hadamard's theorem, sadly. However, it isn't too difficult to reason about this case directly. We know that $\exp_N : B_{\pi}(0) \to S^n - \{S\}$
is a diffeomorphism where $N$ is the North pole, $S$ is the South pole and $B_{\pi}(0) \subset T_N S^n$. Let $\varphi_N$ be the corresponding normal coordinate chart.
From here, we select some other point $\varphi_N(x) = N' \neq \{N, S\}$ which gives a normal coordinate chart $\varphi_{N'} : B_{\pi}(0) \to S^n - \{S'\}$, where $S'$ is antipodal to $N'$.
We similarly can choose some arbitrary point $p \in M$ and we get a local diffeomorphism $\psi : B_{\pi}(0) \to M$ centred at $p$ again by applying Lemma 6. We let $q = \psi(x)$ and finally
note that we have local diffeomorphism $\eta : B_{\pi}(0) \to M$ centred at $q$. We want to paste together all of these local isometries (when we endow Euclidean ball with the pullback metrics) to obtain a global one.
We will clearly have a composition
$\psi \circ \varphi_N^{-1} : S^n - \{S\} \to M$ which is a local isometry, as well as $\eta \circ \varphi_{N'}^{-1}$. To show that two local isometries agree on a connected manifold, we know that
if suffices to show that their derivatives agree at a point. Note that both of these maps send $N'$ to $q$. However, their derivatives
at $q$ may differ. To remedy this situation, consider the map $F = \eta^{-1} \circ \psi \circ \varphi_N^{-1} \circ \varphi_{N'}$ which is defined on a small neighbourhood (so that $\eta$ is in fact invertible)
of the origin (it sends $0$ to itself). Thus, we obtain a linear map $L : \mathbb{R}^n \to \mathbb{R}^n$ given by $L = DF(0)$. This will itself be an isometry of Euclidean space,
as both $\eta^{-1} \circ \psi$ and $\varphi_N^{-1} \circ \varphi_{N'}$ are isometries near the origin.
Instead of using $\eta \circ \varphi_{N'}^{-1}$, we replace it with the map $\eta \circ L \circ \varphi_{N'}^{-1}$. Since $L(0) = 0$, it is easy to see that this new map still sends $N'$ to $q$, it is still an
isometry onto its image as $L$ is an isometry of Euclidean space, and moreover, the derivative of this new function is clearly the same as the derivative of $\psi \circ \varphi_N^{-1}$ at $N'$. Therefore,
The two local isometries glue together to give a well defined function $\Phi : S^n \to M$ which is a local isometry.

To finish the proof, note that $\Phi(S^n)$ is compact, and since $M$ is Hausdorff, it is closed. On the other hand, since $\Phi$ is a local diffeomorphism, its image is also open. Since $M$ is
connected, it follows that $\Phi(S^n) = M$. Moreover, because $S^n$ is compact, the fibres of $\Phi$ must be finite, as if we had a sequence of distinct $z_n \in \Phi^{-1}(z)$ each of which is contained
in a neighbourhood $U_n$ homeomorphic to its image, thus not containing any of the other $z_m$, we could never pass to a finite subcover. But $\Phi^{-1}(z)$ is compact, being a closed subset of a
compact space, so this is a contradiction. It follows immediately that $\Phi$ is a smooth covering map, and since $M$ is simply-connected, it is a diffeomorphism. Moreover, since it was already shown
to be a local isometry, it is in fact a global isometry.

----------

This is yet another amazing result. Given some $(M, g)$ (connected/complete) of constant sectional curvature, we may always construct the universal covering manifold $\pi : \widetilde{M} \to M$
and endow it with $\pi^{*} g$, so that $(\widetilde{M}, \pi^{*} g)$ is simply-connected, has constant sectional curvature, and moreover is complete (as we can take geodesic segment in $\widetilde{M}$,
project by local isometry $\pi$ to a geodesic segment in $M$, extend to all time, then lift to an all-time extension in $\widetilde{M}$ of the original geodesic). Therefore, $(\widetilde{M}, \pi^{*} g)$
will be isometric to one of the model spaces with its canonical metric, so WLOG we assume $\widetilde{M}$ is one of the model spaces and $\pi^{*} g = h$, the corresponding metric.
It is a basic fact from differential topology that $M$ is diffeomorphic to $\widetilde{M}/\Gamma$: its universal covering
manifold quotiented by the action of the group of deck transformations of the cover $\pi : \widetilde{M} \to M$, each of which is an automorphism of the cover and satisfies $\pi \circ f = \pi$ hence $f^{*} \pi^{*} g = \pi^{*} g$,
so it is in fact an isometry. In other words, we are quotienting by the action of some subgroup of $\text{Iso}(\widetilde{M}, h)$. It isn't too difficult to see that $\widetilde{M}/\Gamma$ endowed
with the covering metric is isometric to $(M, g)$. Thus:

*Corollary 11.* The /only way/ that a complete connected space of constant sectional curvature arises is by taking one of the model spaces $\{\mathbb{H}^n_{R}, \mathbb{R}^n, S^n_{R}\}$ (with its
canonical metric, constant curvature $R$), quotienting by some subgroup of the isometries, and endowing the quotient manifold with the covering metric.

Amazing!

* Postscript: Cartan's theorem (maximum power)

In the section where we wrote down explicitly the local form of metrics of constant curvature in normal coordinates, there is a somewhat stronger result that allows us to compare
the local forms of metrics on /arbitrary/ pairs of Riemannian manifolds. In particular,

*Theorem* (Cartan). Suppose $(M, g)$ and $(N, h)$ are Riemannian manifolds of the same dimension, $p \in M$ and $q \in N$. Suppose $i : T_p M \to T_q N$ is a linear isometry (where
we equip these vector spaces with $g_p$ and $h_q$ respectively). It follows that we may restrict $i$ to a map of $\varepsilon$ -balls $B_{\varepsilon}(0) \to B_{\varepsilon}(0)$. Pick
$\varepsilon$ sufficiently small so that $\exp_p : B_{\varepsilon}(0) \to M$ and $\exp_q : B_{\varepsilon}(0) \to N$ are both local diffeomorphisms. Suppose we fix some
geodesic $\gamma : [0, 1] \to M$ in $B$ such that $\gamma(0) = p$. We can obtain geodesic $\widetilde{\gamma} : [0, 1] \to N$ contained in $\exp_q(B_{\varepsilon}(0)) = B'$
with $\widetilde{\gamma}(0) = q$ and $\dot{\widetilde{\gamma}}(0) = i(\dot{\gamma}(0))$. Note that $\widetilde{\gamma}$ is defined on $[0, 1]$ because it has the same speed as $\gamma$.
Let $P : T_p M \to T_{\gamma(t)} M$ and $\widetilde{P} : T_q N \to T_{\widetilde{\gamma}(t)}$ be the parallel transport maps. From here, if it is true that

\begin{equation}
(P^{*} R_M)(X, Y, Z, W) = (i^{*} \widetilde{P}^{*} R_N)(X, Y, Z, W)
\end{equation}

for all $X, Y, Z, W \in T_p M$, then $i$ will actually be an isometry $(B_{\varepsilon}(0), \exp_p^{*} g) \to (B_{\varepsilon}(0), \exp_q^{*} h)$ (i.e. when we equip the tangent spaces with their pullback metrics).
Note that as an immediate corollary, if we have constant sectional curvature, then any isometry $i : (T_p M, g_p) \to (T_q N, h_q)$ will be an isometry when these spaces
are equipped with their pullback metrics. We showed earlier that when $(M, g)$ has constant curvature, and we defined an arbitrary isometry $\Phi : (\mathbb{R}^n, \langle \cdot, \cdot \rangle) \to (T_p M, g_p)$, then
$\Phi^{*} \exp_p^{*} g$ would be a metric on $B_{\varepsilon}(0) \subset \mathbb{R}^n$ independent of the chosen isometry (in particular, the pulled-back metric we found is rotationally symmetric!).
Thus, Cartan's theorem is a generalization of what we showed earlier.
