#+TITLE:The Stokes groupoids I
#+DESCRIPTION:Directory
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+HTML_HEAD: <style> body {font-size:15px;} </style>

/Originally posted:/

-------------

* Introduction

The goal of this blog post (actually, this will probably be a /series/ of blog posts) is to go through the details of the paper of Gualtieri, Li, and Pym, /The Stokes groupoids/.
The target audience of this post is someone who, like me, is familar with some of the very basic theory of Lie groupoids and algebroids, but it still pretty much a beginner in the
field. I will be writing this post in a very "stream-of-counscious" way, taking many digressions to explain basic pieces of theory with which I wasn't familiar at the time of writing.

* Motivation

Let us first go through the motivation for the paper's results. The authors begin by summarizing the Riemann-Hilbert correspondence: an equivalence between flat connection over a manifold
and representations of its fundamental group, $\rho : \pi_1(M, x_0) \rightarrow \text{End}(V)$. They explain this correspondence as follows: we know that a flat connection $\nabla : \Gamma(TX) \times \Gamma(E) \rightarrow \Gamma(E)$
on a vector bundle $E \to X$ (i.e. one which satisfies $[\nabla_V, \nabla_W] = \nabla_{[V, W]}$ for $V, W \in \Gamma(TX)$) is a representation of the "tautological" Lie algebroid $TX$. Of course,
we also know that given any connection and curve $\gamma$ from $a \in M$ to $b \in M$, there is a parallel transport isomorphism $P_{\gamma} : E_a \rightarrow E_b$. Recall:

*Definition 2.1.* If $G$ is a groupoid, a functor $F : G \rightarrow \text{Core}(\text{Vect})$, where the core of the category of vector spaces is the category obtained from discarding all arrows
which are not isomorphisms, thus making $\text{Core}(\text{Vect})$ a groupoid itself. It is clear that in the case that $G$ is a groupoid (has a single element), this definition is equivalent to the
usual representation of a group.

From here, define $F : \Pi_1(X) \rightarrow \text{Core}(\text{Vect})$ by taking $a \in X$ to $E_a$ and $[\gamma] \in \text{Mor}_{\Pi_1(X)}(a, b)$ to $P_{\gamma} : E_a \rightarrow E_b$.
This map is well-defined in the case that $\nabla$ is flat, by the standard result:

*Theorem 2.1.* If $\nabla$ is a flat connection on $E \to X$, then the parallel transport operator induced by path-homotopic paths are equal.

/Proof./ Let $H : I \times I \rightarrow X$ be a path-homotopy between paths from $a$ to $b$, so that $H(0, s) = a$ and $H(1, s) = b$ for all $s$. Let $\gamma(t) = H(t, 0)$ and $\sigma(t) = H(t, 1)$.
Our first goal is to find smooth $V : I \times I \rightarrow TX$ such that $V(t, s) \in T_{H(t, s)} X$, $V(0, s) = V_0$, and

\begin{equation}
D_t V = 0
\end{equation}

so that for each fixed $s$, vector field $t \mapsto V(t, s)$ is parallel along $t \mapsto H(t, s)$. By expanding in coordinates, this becomes a first-order ODE for which we have existence and uniqueness,
so such a function $V$ does exist. The map $V_0 \mapsto V(1, 0)$ is the parallel transport along $\gamma$ and the map $V_0 \mapsto V(1, 1)$ is the parallel transport along $\sigma$. We want to
show that $V(1, 0) = V(1, 1)$. It is a standard fact in Riemannian geometry that

\begin{equation}
D_t D_s V - D_s D_t V = R(\partial_s H, \partial_t H) V
\end{equation}

But in the case that our connection is flat, $R = 0$, so it follows that $D_t D_s V = D_s D_t V = 0$. Note that $V(0, s) = V_0$ for all $s$, so $D_s V(0, s) = 0$. Thus, by uniqueness,
$D_s V(t, s)$ is the parallel transport along $t \mapsto H(t, s)$ of $0$, so $D_s V(t, s) = 0$ for all $(t, s)$. It follows that $V(1, 0) = V(1, 1)$, as desired. $\blacksquare$

It is now clear that $F$ is a functor (preserves composition of arrows). Via the map which takes a flat connection/Lie algebroid representation to the corresponding representation $F$ of
the fundamental groupoid, the paper claim that the categories $\text{Rep}(TX)$ and $\text{Rep}(\Pi_1(X))$ are equivalent. I don't really know what the inverse map is yet. We know that the categories $\Pi_1(X)$ and $\pi_1(X, p)$ are equivalent,
so $\text{Rep}(\Pi_1(X)) \simeq \text{Rep}(\pi_1(X, p))$ as well.

We now move on to the contribution of the paper: we wish to study the case where the connection is allowed to have singularities along a divisor $D$ in $X$, introducing a new groupoid $\Pi_1(X, D)$, and by extension
studying the Riemann-Hilbert correspondence with respect to this new, generalized groupoid.

* Lie algebroids and meromorphic connections

First, let $X$ be a smooth complex curve. Let $D$ be an effective divisor, which is an element of the free Abelian group generated by the points of $X$. A generic element is of the form

\begin{equation}
d = \sum_{i = 1}^{n} n_i x_i
\end{equation}

for $n_i \in \mathbb{Z}$ and $x_i \in X$. One can define a divisor $(f)$ of a meromorphic function $f$ on $X$ (i.e. a holomorphic function $f : X \rightarrow S^2$), where $(f) = \sum_{p \in X} \text{ord}_f(p) p$ where
we are assuming $f$ has a finite number of roots/poles in $X$.
